web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - mongo
    - geth
    - geth-mainnet

mongo:
  image: mongo

geth:
  build: ./support/geth
  environment:
    - GETHFLAGS=--testnet

geth-mainnet:
  build: ./support/geth
  environment:
    - GETHFLAGS=