web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - mongo
    - geth:geth-testnet

mongo:
  image: mongo

geth-testnet:
  build: ./support/geth
  environment:
    - GETHFLAGS=--testnet

geth-mainnet:
  build: ./support/geth
  environment:
    - GETHFLAGS=