web:
  build: .
  ports:
    - "8000:8000"
  links:
    - redis
    - geth

redis:
  image: redis
  ports:
    - "6379:6379"

geth:
  build: ./geth
  environment:
    - GETHFLAGS=--dev
  ports:
    - "8545:8545"